### ISSUE TITLE
Release pipeline

### ISSUE THREAD

**Issue by ma499** [Aqovia/VisualStudio.ExtensionPack#2]
Add a release pipeline so that new versions are automatically pushed to the Visual Studio Marketplace.

**Comment by margani** [comment]
@ma499 I need Github and VS Marketplace connections in Azure DevOps
![VS Marketplace](https://msftplayground.com/wp-content/uploads/2018/11/2018-10-26_09-17-33.png)

**Comment by ma499** [comment]
Maybe it should be a Github Action now?

**Comment by ma499** [comment]
I found a blog that might be helpful: https://cezarypiatek.github.io/post/develop-vsextension-with-github-actions/

**Comment by margani** [comment]
This is done in #4
